#!/usr/bin/env bash

SELF=$(basename "$0")
COMMAND="$1"
KERNEL_VERSION="$2"

[[ "$KERNEL_INSTALL_INITRD_GENERATOR" == "booster" ]] || exit 0
[[ "$COMMAND" == "add" ]] || exit 0

EXEC=("booster" "build" "--force")
if [[ -n "$KERNEL_INSTALL_BOOSTER_UNIVERSAL" ]]; then
    EXEC+=("--universal")
fi
EXEC+=(
    "--kernel-version=$KERNEL_VERSION"
    "$KERNEL_INSTALL_STAGING_AREA/initrd"
)

echo "+$SELF: ${EXEC[*]}"
"${EXEC[@]}"
