---
- name: Tests foundation
  hosts: debug_local
  gather_facts: false
  tasks:
    #
    # foundation.user.layout
    #
    - name: Test foundation.user.layout
      ansible.builtin.assert:
        that:
          - lookup('foundation.user.layout', 'dot', _ulayout) == '/dot'
      vars:
        _ulayout:
          default: /default
          dot: /dot
          xdg:
            link: /xdg-link
    #
    # foundation.user.layout
    #
    - name: Test foundation.user.layout
      foundation.user.layout:
        wipe: never
        layout: xdg
      vars:
        cache:
          default: /default
          wipe: always
          dot: /dot
          xdg:
            link: /xdg-link
      register: ulayout
    #
    # foundation.user.env
    #
    - name: Test foundation.user.env
      foundation.user.env:
        section: test
        home: /home/user
        subs:
          XDG_CONFIG_HOME: /home/user/.config
      environment:
        MYAPP_CONFIG: /home/user/.config/myapp
    #
    # foundation.user.package
    #
    - name: Test foundation.user.package
      foundation.user.packages:
        wipe: always
        home: /home/user
      vars:
        install:
          - foo
        remove:
          - bar
    #
    # foundation.system.env
    #
    - name: Test foundation.system.env
      foundation.system.env:
      environment:
        SYSTEM_VAR: VALUE
    #
    # foundation.system.kernel
    #
    - name: Test foundation.system.kernel
      foundation.system.kernel:
        headless: true
      environment:
        flag: true
        list:
          - auto
          - force
        option: libata
    #
    # foundation.system.services
    #
    - name: Test foundation.system.services
      foundation.system.services:
        headless: true
      vars:
        units:
          - myservice
        state:
          disable: true
    #
    # foundation.system.stop
    #
    - name: Test foundation.system.stop
      foundation.system.stop:
        headless: true
      vars:
        processes:
          - myproc
        services:
          - myservice
    #
    # foundation.system.packages
    #
    - name: Test foundation.system.packages
      foundation.system.packages:
        sync: false
        force: false
      vars:
        install:
          - foo
        remove:
          - bar
    #
    # foundation.persist.from
    #
    - name: Test foundation.persist.from
      foundation.persist.from:
        base: /mydir
        persist: "{{ playbook_dir }}/persist"
      vars:
        shells:
          - key: fookey/shell
            dir: ./my-dir
            cmd: echo 123
        archives:
          - key: barkey/archive
            dir: /tmp
            perms: owner:group
    #
    # foundation.persist.to
    #
    - name: Test foundation.persist.to
      foundation.persist.to:
        base: /mydir
        persist: "{{ playbook_dir }}/persist"
      vars:
        shells:
          - key: some/path
            dir: ./foo
            cmd: echo 123
        archives:
          - key: some/another
            dir: /tmp
            include:
              - foo
    #
    # foundation.persist.gpg
    #
    - name: Test foundation.persist.gpg
      foundation.persist.gpg:
        home: /home/user
        layout: dot
      vars:
        keys:
          - foo
      register: gpg

    # foundation.files.install
    #
    - name: Test foundation.files.install
      foundation.files.install:
        wipe: always
        perms: 755:755:{{ ca_name }}:{{ ca_name }}
      vars:
        targets:
          - dir: /something
          - file: /some
            content: foobar
            perms: "644"
    #
    # foundation.files.net_archive
    #
    - name: Test foundation.files.net_archive
      foundation.files.net_archive:
        url: https://github.com/sharkdp/bat/releases/download/v0.25.0/bat-v0.25.0-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/foo
        perms: owner:group
        strip: 1
        creates:
          - ./bat
