cc_test(
    name = "util",
    size = "small",
    srcs = [
        "util/util_test.cc",
    ],
    deps = [
        "//src:util",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    copts = [
        "-Isrc",
    ],
)
