---
- name: Configure system directories
  tags: apex-system-dirs-main
  block:
    - name: Create system directories
      become: true
      foundation.files.install:
        wipe: "{{ aa_wipe }}"
        perms: 755:755:root:root
        create: true
      vars:
        targets:
          - dir: "{{ ea_dir_apps }}"
          - dir: "{{ ea_dir_bin }}"
          - dir: "{{ ea_dir_entries }}"
          - dir: "{{ ea_dir_stubs }}"

          - dir: "{{ ea_dir_addons }}"
            wipe: never
